#!/bin/bash

echo "🎬 Premium Feature Demo"
echo "======================"
echo ""
echo "✅ Server should be running on port 3001"
echo ""
echo "📋 Demo Steps:"
echo ""
echo "1. Test Backend API (Optional):"
echo "   node test-premium-endpoints.js"
echo ""
echo "2. Open Premium Quiz:"
echo "   http://localhost:3001/premium/quiz"
echo ""
echo "3. Test Flow:"
echo "   - Take quiz (1st attempt) ✅"
echo "   - Take quiz again (2nd attempt) ✅"
echo "   - Try 3rd time → See paywall! 🔒"
echo ""
echo "4. See Gated Content:"
echo "   - Complete quiz to see results"
echo "   - Notice: Only 2 articles, 1 insight, 1 podcast shown"
echo "   - Paywall sections appear below locked content"
echo ""
echo "5. Compare with Regular Routes:"
echo "   - http://localhost:3001/quiz (no limits)"
echo "   - http://localhost:3001/results (full content)"
echo ""
echo "🔗 Quick Links:"
echo "   Premium Quiz: http://localhost:3001/premium/quiz"
echo "   Premium Results: http://localhost:3001/premium/results"
echo "   Regular Quiz: http://localhost:3001/quiz"
echo "   Home: http://localhost:3001/"
echo ""
echo "📚 Full Guide: See DEMO_GUIDE.md"
echo ""

